# Generated by Django 5.1.3 on 2024-11-09 11:13

import PartyHub_Project.Party.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a unique title of at least 5 characters.', max_length=70, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'The title must be at least 5 characters long.')])),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateTimeField(help_text='Set the start date and time for the event.')),
                ('end_date', models.DateTimeField(help_text='Set the end date and time for the event.')),
                ('location', models.TextField(max_length=70)),
                ('party_type', models.CharField(choices=[('metal', 'Metal'), ('rap', 'Rap'), ('chalga', 'Chalga'), ('disco', 'Disco'), ('drinking', 'Drinking'), ('drinking_and_smoking', 'Drinking and smoking'), ('normal', 'Normal'), ('gaming', 'Gaming'), ('meetup', 'Meetup'), ('other', 'Other')], help_text="Select an event type, or choose 'Other' to specify your own.", max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'Party type must be at least characters long.')])),
                ('available_spots', models.PositiveIntegerField(help_text='Minimum of 2 people required.', validators=[django.core.validators.MinValueValidator(2, "Available spots can't be less than 2!")])),
                ('picture', models.ImageField(blank=True, help_text='Upload an image with a maximum size of 6MB.', null=True, upload_to='images/', validators=[PartyHub_Project.Party.validators.MaxSizeValidator(6)])),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Optional: Deadline for participant registration.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier based on the title.', null=True, unique=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
