# Generated by Django 5.1.3 on 2024-11-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier based on the title.', max_length=100, null=True, unique=True),
        ),
    ]
