# Generated by Django 5.1.3 on 2024-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
