# Generated by Django 5.1.3 on 2024-12-03 22:49

import PartyHub_Project.Party.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0003_alter_party_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('metal', 'Metal'), ('rap', 'Rap'), ('chalga', 'Chalga'), ('disco', 'Disco'), ('birthday', 'Birthday'), ('wedding', 'Wedding'), ('conference', 'Conference'), ('drinking', 'Drinking'), ('drinking_and_smoking', 'Drinking and smoking'), ('gaming', 'Gaming'), ('meetup', 'Meetup'), ('other', 'Other')], help_text="Select an event type, or choose 'Other' to specify your own.", max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'Party type must be at least characters long.')]),
        ),
        migrations.AlterField(
            model_name='party',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload an image with a maximum size of 6MB.', null=True, upload_to='party_imgs/', validators=[PartyHub_Project.Party.validators.MaxSizeValidator(5)]),
        ),
    ]
