# Generated by Django 5.1.3 on 2024-12-04 00:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0004_alter_party_party_type_alter_party_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image with a maximum size of 6MB.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
