# Generated by Django 5.1.3 on 2024-12-04 00:41

import PartyHub_Project.Party.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0005_alter_party_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload an image with a maximum size of 6MB.', null=True, upload_to='party_imgs/', validators=[PartyHub_Project.Party.validators.MaxSizeValidator(5)]),
        ),
    ]
