# Generated by Django 5.1.3 on 2024-12-09 21:54

import PartyHub_Project.Party.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0006_alter_party_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image with a maximum size of 6MB.', max_length=255, null=True, validators=[PartyHub_Project.Party.validators.MaxSizeValidator(5)], verbose_name='image'),
        ),
    ]
