# Generated by Django 5.1.3 on 2024-11-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='event',
            new_name='party',
        ),
    ]
