# Generated by Django 5.1.3 on 2024-11-06 21:21

import PartyHub_Project.Accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
                ('objects', PartyHub_Project.Accounts.managers.UserProfileManager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, max_length=300, to='Accounts.userprofile'),
        ),
    ]
