# Generated by Django 5.1.3 on 2024-11-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default_img.jpg', upload_to='profiles/'),
        ),
    ]
